# Temporarily disabled very_good_analysis include due to pub cache issues
# include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    public_member_api_docs: false
    # Add basic lint rules for MVP
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
