name: revision
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_vertexai: ^0.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_libraw: ^0.0.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_sign_in: 6.1.5
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
