name: revision
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  # Firebase - Using stable versions compatible with current Android build tools
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.4.3
  crypto: ^3.0.5
  firebase_analytics: ^11.5.2
  # firebase_ai: ^2.2.0  # Removed - using direct REST API instead since Firebase AI Logic doesn't support image input
  firebase_crashlytics: ^4.3.10
  firebase_remote_config: ^5.1.3
  firebase_storage: ^12.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  google_generative_ai: ^0.4.6
  google_sign_in: ^7.1.0
  http: ^1.4.0
  image: ^4.5.4
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  fake_async: ^1.3.1
  faker: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  # very_good_analysis: ^6.0.0 # Temporarily disabled due to pub cache issue

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.development
    - .env.staging
    - .env.production