name: revision
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  # Firebase - Using stable versions compatible with current Android build tools
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.3.3
  firebase_ai: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  http: ^1.4.0
  image: ^4.5.4
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  fake_async: ^1.3.1
  faker: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  # very_good_analysis: ^6.0.0 # Temporarily disabled due to pub cache issue

flutter:
  uses-material-design: true
  generate: true
