// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

// Import environment-specific configurations
import 'firebase_options_dev.dart' as dev;
import 'firebase_options_staging.dart' as staging;
import 'firebase_options_production.dart' as production;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Get environment from compile-time constant
    const environment = String.fromEnvironment('ENVIRONMENT', defaultValue: 'development');
    
    // Return environment-specific options
    switch (environment) {
      case 'production':
        return production.DefaultFirebaseOptions.currentPlatform;
      case 'staging':
        return staging.DefaultFirebaseOptions.currentPlatform;
      case 'development':
      default:
        return dev.DefaultFirebaseOptions.currentPlatform;
    }
  }
}
    }
  }