// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _getWebOptions();
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _getAndroidOptions();
      case TargetPlatform.iOS:
        return _getIOSOptions();
      case TargetPlatform.macOS:
        // Or handle macOS specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for macOS.',
        );
      case TargetPlatform.windows:
        // Or handle windows specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for windows.',
        );
      case TargetPlatform.linux:
        // Or handle linux specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for linux.',
        );
      case TargetPlatform.fuchsia:
        // Or handle fuchsia specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOEvNSrcXqh0n9FD4deqGxFRYhBmfbmg',
    appId: '1:286965129060:web:c43635c372975dfd13a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    authDomain: 'revision-464202.firebaseapp.com',
    storageBucket: 'revision-464202.firebasestorage.app',
    measurementId: 'G-M787R1D63W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcmiB-92MRTUx0kkMceMPgKdEUkiDxrU',
    appId: '1:286965129060:android:3199446fd73253bb13a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    storageBucket: 'revision-464202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5Bao49F2y8h5PBvOdzDFyKd7NTaZD5s',
    appId: '1:286965129060:ios:306d857dd0768ca113a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    storageBucket: 'revision-464202.firebasestorage.app',
    iosBundleId: 'com.sly.revision',
  );

}