// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Or handle macOS specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for macOS.',
        );
      case TargetPlatform.windows:
        // Or handle windows specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for windows.',
        );
      case TargetPlatform.linux:
        // Or handle linux specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for linux.',
        );
      case TargetPlatform.fuchsia:
        // Or handle fuchsia specifically if you have a separate configuration
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrnLSckHLO0nhPudg7-aClqgrvtjy9_Y',
    appId: '1:80100619406:web:d8f4c8556e3fb468aa45df',
    messagingSenderId: '80100619406',
    projectId: 'revision-fc66c',
    authDomain: 'revision-fc66c.firebaseapp.com',
    storageBucket: 'revision-fc66c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrnLSckHLO0nhPudg7-aClqgrvtjy9_Y',
    appId: '1:80100619406:android:c825dd556e3fb468aa45df',
    messagingSenderId: '80100619406',
    projectId: 'revision-fc66c',
    storageBucket: 'revision-fc66c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJrnLSckHLO0nhPudg7-aClqgrvtjy9_Y',
    appId: '1:80100619406:ios:d8f4c8556e3fb468aa45df',
    messagingSenderId: '80100619406',
    projectId: 'revision-fc66c',
    storageBucket: 'revision-fc66c.appspot.com',
    iosBundleId: 'com.sly.revision',
  );
}
