// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOEvNSrcXqh0n9FD4deqGxFRYhBmfbmg',
    appId: '1:286965129060:web:c43635c372975dfd13a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    authDomain: 'revision-464202.firebaseapp.com',
    storageBucket: 'revision-464202.firebasestorage.app',
    measurementId: 'G-M787R1D63W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcmiB-92MRTUx0kkMceMPgKdEUkiDxrU',
    appId: '1:286965129060:android:3199446fd73253bb13a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    storageBucket: 'revision-464202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5Bao49F2y8h5PBvOdzDFyKd7NTaZD5s',
    appId: '1:286965129060:ios:306d857dd0768ca113a471',
    messagingSenderId: '286965129060',
    projectId: 'revision-464202',
    storageBucket: 'revision-464202.firebasestorage.app',
    iosBundleId: 'com.sly.revision',
  );
}
